// Code generated by ModelGenerator gengolibmodel. DO NOT EDIT.

package model

import (
	"github.com/PVKonovalov/libiec61850-Go/pkg/iec61850/common"
	imodel "github.com/PVKonovalov/libiec61850-Go/pkg/iec61850/model"
	"github.com/PVKonovalov/libiec61850-Go/pkg/mms"
)

// BuildModel constructs and returns the IEC 61850 data model.
func BuildModel() *imodel.IedModel {
	iedModel := imodel.NewIedModel("SampleIED")

	// Logical Device: Device1
	ld1 := imodel.NewLogicalDevice("Device1", iedModel)

	// Logical Node: LLN0
	ln2 := imodel.NewLogicalNode("LLN0", ld1)

	do3 := imodel.NewDataObject("Mod", ln2)
	da4 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do3)
	da4.TriggerOptions = common.TriggerQualityChanged
	da4.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da5 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do3)
	da5.Value = mms.NewUTCTime(mms.UTCTime{})
	da6 := imodel.NewDataAttribute("ctlModel", common.FC_CF, common.TypeEnumerated, do3)
	da6.Value = mms.NewInt32(0)

	do7 := imodel.NewDataObject("Beh", ln2)
	da8 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do7)
	da8.TriggerOptions = common.TriggerDataChanged
	da8.Value = mms.NewInt32(0)
	da9 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do7)
	da9.TriggerOptions = common.TriggerQualityChanged
	da9.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da10 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do7)
	da10.Value = mms.NewUTCTime(mms.UTCTime{})

	do11 := imodel.NewDataObject("Health", ln2)
	da12 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do11)
	da12.TriggerOptions = common.TriggerDataChanged
	da12.Value = mms.NewInt32(0)
	da13 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do11)
	da13.TriggerOptions = common.TriggerQualityChanged
	da13.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da14 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do11)
	da14.Value = mms.NewUTCTime(mms.UTCTime{})

	do15 := imodel.NewDataObject("NamPlt", ln2)
	da16 := imodel.NewDataAttribute("vendor", common.FC_DC, common.TypeVisibleStr255, do15)
	da16.Value = mms.NewVisibleString("")
	da17 := imodel.NewDataAttribute("swRev", common.FC_DC, common.TypeVisibleStr255, do15)
	da17.Value = mms.NewVisibleString("")
	da18 := imodel.NewDataAttribute("d", common.FC_DC, common.TypeVisibleStr255, do15)
	da18.Value = mms.NewVisibleString("")
	da19 := imodel.NewDataAttribute("configRev", common.FC_DC, common.TypeVisibleStr255, do15)
	da19.Value = mms.NewVisibleString("")
	da20 := imodel.NewDataAttribute("ldNs", common.FC_EX, common.TypeVisibleStr255, do15)
	da20.Value = mms.NewVisibleString("")

	ds21 := &imodel.DataSet{Name: "LLN0$dataset1"}
	ds21.Members = append(ds21.Members, imodel.DataSetMember{Reference: "Device1/LLN0.Mod.q", FC: common.FC_ST})
	ds21.Members = append(ds21.Members, imodel.DataSetMember{Reference: "Device1/MMXU1.Mod.q", FC: common.FC_ST})
	ds21.Members = append(ds21.Members, imodel.DataSetMember{Reference: "Device1/MMXU1.Mod.ctlModel", FC: common.FC_CF})
	iedModel.DataSets = append(iedModel.DataSets, ds21)

	iedModel.RCBs = append(iedModel.RCBs, &imodel.ReportControlBlock{
		Name:         "LLN0_Events_BuffRep01",
		DataSetRef:   "dataset1",
		Buffered:     true,
		RptID:        "LLN0$RP$brcbEV1",
		ConfRev:      1,
		TrgOps:       common.TriggerDataChanged | common.TriggerIntegrity | common.TriggerGI,
		OptFields:    common.ReportOptSeqNum | common.ReportOptTimeStamp | common.ReportOptReasonForInclusion | common.ReportOptDataSet | common.ReportOptBufferOverflow | common.ReportOptEntryID | common.ReportOptConfRev,
		BufTime:      50,
		IntgPd:       900000,
		Indexed:      true,
		MaxInstances: 1,
		LDInst:       "Device1",
		LNName:       "LLN0",
	})

	// Logical Node: LPHD1
	ln22 := imodel.NewLogicalNode("LPHD1", ld1)

	do23 := imodel.NewDataObject("PhyNam", ln22)
	da24 := imodel.NewDataAttribute("vendor", common.FC_DC, common.TypeVisibleStr255, do23)
	da24.Value = mms.NewVisibleString("")

	do25 := imodel.NewDataObject("PhyHealth", ln22)
	da26 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do25)
	da26.TriggerOptions = common.TriggerDataChanged
	da26.Value = mms.NewInt32(0)
	da27 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do25)
	da27.TriggerOptions = common.TriggerQualityChanged
	da27.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da28 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do25)
	da28.Value = mms.NewUTCTime(mms.UTCTime{})

	do29 := imodel.NewDataObject("Proxy", ln22)
	da30 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeBoolean, do29)
	da30.TriggerOptions = common.TriggerDataChanged
	da30.Value = mms.NewBoolean(false)
	da31 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do29)
	da31.TriggerOptions = common.TriggerQualityChanged
	da31.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da32 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do29)
	da32.Value = mms.NewUTCTime(mms.UTCTime{})

	// Logical Node: DGEN1
	ln33 := imodel.NewLogicalNode("DGEN1", ld1)

	do34 := imodel.NewDataObject("Mod", ln33)
	da35 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do34)
	da35.TriggerOptions = common.TriggerQualityChanged
	da35.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da36 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do34)
	da36.Value = mms.NewUTCTime(mms.UTCTime{})
	da37 := imodel.NewDataAttribute("ctlModel", common.FC_CF, common.TypeEnumerated, do34)
	da37.Value = mms.NewInt32(0)

	do38 := imodel.NewDataObject("Beh", ln33)
	da39 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do38)
	da39.TriggerOptions = common.TriggerDataChanged
	da39.Value = mms.NewInt32(0)
	da40 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do38)
	da40.TriggerOptions = common.TriggerQualityChanged
	da40.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da41 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do38)
	da41.Value = mms.NewUTCTime(mms.UTCTime{})

	do42 := imodel.NewDataObject("Health", ln33)
	da43 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do42)
	da43.TriggerOptions = common.TriggerDataChanged
	da43.Value = mms.NewInt32(0)
	da44 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do42)
	da44.TriggerOptions = common.TriggerQualityChanged
	da44.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da45 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do42)
	da45.Value = mms.NewUTCTime(mms.UTCTime{})

	do46 := imodel.NewDataObject("NamPlt", ln33)
	da47 := imodel.NewDataAttribute("vendor", common.FC_DC, common.TypeVisibleStr255, do46)
	da47.Value = mms.NewVisibleString("")
	da48 := imodel.NewDataAttribute("swRev", common.FC_DC, common.TypeVisibleStr255, do46)
	da48.Value = mms.NewVisibleString("")
	da49 := imodel.NewDataAttribute("d", common.FC_DC, common.TypeVisibleStr255, do46)
	da49.Value = mms.NewVisibleString("")

	do50 := imodel.NewDataObject("OpTmh", ln33)
	da51 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do50)
	da51.TriggerOptions = common.TriggerDataChanged
	da51.Value = mms.NewInt32(0)
	da52 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do50)
	da52.TriggerOptions = common.TriggerQualityChanged
	da52.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da53 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do50)
	da53.Value = mms.NewUTCTime(mms.UTCTime{})

	do54 := imodel.NewDataObject("GnOpSt", ln33)
	da55 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do54)
	da55.TriggerOptions = common.TriggerDataChanged
	da55.Value = mms.NewInt32(0)
	da56 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do54)
	da56.TriggerOptions = common.TriggerQualityChanged
	da56.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da57 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do54)
	da57.Value = mms.NewUTCTime(mms.UTCTime{})

	do58 := imodel.NewDataObject("OpTmsRs", ln33)
	da59 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do58)
	da59.TriggerOptions = common.TriggerDataChanged
	da59.Value = mms.NewInt32(0)
	da60 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do58)
	da60.TriggerOptions = common.TriggerQualityChanged
	da60.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da61 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do58)
	da61.Value = mms.NewUTCTime(mms.UTCTime{})

	do62 := imodel.NewDataObject("TotWh", ln33)
	da63 := imodel.NewDataAttribute("mag", common.FC_MX, common.TypeConstructed, do62)
	da63.TriggerOptions = common.TriggerDataChanged
	da64 := imodel.NewSubDataAttribute("f", common.FC_MX, common.TypeFLOAT32, da63)
	da64.TriggerOptions = common.TriggerDataChanged
	da64.Value = mms.NewFloat32(0)
	da65 := imodel.NewDataAttribute("q", common.FC_MX, common.TypeQuality, do62)
	da65.TriggerOptions = common.TriggerQualityChanged
	da65.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da66 := imodel.NewDataAttribute("t", common.FC_MX, common.TypeTimestamp, do62)
	da66.Value = mms.NewUTCTime(mms.UTCTime{})

	// Logical Node: DSCH1
	ln67 := imodel.NewLogicalNode("DSCH1", ld1)

	do68 := imodel.NewDataObject("Mod", ln67)
	da69 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do68)
	da69.TriggerOptions = common.TriggerQualityChanged
	da69.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da70 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do68)
	da70.Value = mms.NewUTCTime(mms.UTCTime{})
	da71 := imodel.NewDataAttribute("ctlModel", common.FC_CF, common.TypeEnumerated, do68)
	da71.Value = mms.NewInt32(0)

	do72 := imodel.NewDataObject("Beh", ln67)
	da73 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do72)
	da73.TriggerOptions = common.TriggerDataChanged
	da73.Value = mms.NewInt32(0)
	da74 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do72)
	da74.TriggerOptions = common.TriggerQualityChanged
	da74.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da75 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do72)
	da75.Value = mms.NewUTCTime(mms.UTCTime{})

	do76 := imodel.NewDataObject("Health", ln67)
	da77 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do76)
	da77.TriggerOptions = common.TriggerDataChanged
	da77.Value = mms.NewInt32(0)
	da78 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do76)
	da78.TriggerOptions = common.TriggerQualityChanged
	da78.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da79 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do76)
	da79.Value = mms.NewUTCTime(mms.UTCTime{})

	do80 := imodel.NewDataObject("NamPlt", ln67)
	da81 := imodel.NewDataAttribute("vendor", common.FC_DC, common.TypeVisibleStr255, do80)
	da81.Value = mms.NewVisibleString("")
	da82 := imodel.NewDataAttribute("swRev", common.FC_DC, common.TypeVisibleStr255, do80)
	da82.Value = mms.NewVisibleString("")
	da83 := imodel.NewDataAttribute("d", common.FC_DC, common.TypeVisibleStr255, do80)
	da83.Value = mms.NewVisibleString("")

	do84 := imodel.NewDataObject("SchdSt", ln67)
	da85 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do84)
	da85.TriggerOptions = common.TriggerDataChanged
	da85.Value = mms.NewInt32(0)
	da86 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do84)
	da86.TriggerOptions = common.TriggerQualityChanged
	da86.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da87 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do84)
	da87.Value = mms.NewUTCTime(mms.UTCTime{})

	imodel.NewDataObject("SchdId", ln67)

	imodel.NewDataObject("SchdCat", ln67)

	imodel.NewDataObject("SchdTyp", ln67)

	do91 := imodel.NewDataObject("SchdAbsTm", ln67)
	da92 := imodel.NewDataAttribute("val", common.FC_SP, common.TypeFLOAT32, do91)
	da92.TriggerOptions = common.TriggerDataChanged
	da92.Value = mms.NewFloat32(0)
	da93 := imodel.NewDataAttribute("time", common.FC_SP, common.TypeTimestamp, do91)
	da93.TriggerOptions = common.TriggerDataChanged
	da93.Value = mms.NewUTCTime(mms.UTCTime{})

	// Logical Node: MMXU1
	ln94 := imodel.NewLogicalNode("MMXU1", ld1)

	do95 := imodel.NewDataObject("Mod", ln94)
	da96 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do95)
	da96.TriggerOptions = common.TriggerQualityChanged
	da96.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da97 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do95)
	da97.Value = mms.NewUTCTime(mms.UTCTime{})
	da98 := imodel.NewDataAttribute("ctlModel", common.FC_CF, common.TypeEnumerated, do95)
	da98.Value = mms.NewInt32(0)

	do99 := imodel.NewDataObject("Beh", ln94)
	da100 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do99)
	da100.TriggerOptions = common.TriggerDataChanged
	da100.Value = mms.NewInt32(0)
	da101 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do99)
	da101.TriggerOptions = common.TriggerQualityChanged
	da101.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da102 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do99)
	da102.Value = mms.NewUTCTime(mms.UTCTime{})

	do103 := imodel.NewDataObject("Health", ln94)
	da104 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do103)
	da104.TriggerOptions = common.TriggerDataChanged
	da104.Value = mms.NewInt32(0)
	da105 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do103)
	da105.TriggerOptions = common.TriggerQualityChanged
	da105.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da106 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do103)
	da106.Value = mms.NewUTCTime(mms.UTCTime{})

	do107 := imodel.NewDataObject("NamPlt", ln94)
	da108 := imodel.NewDataAttribute("vendor", common.FC_DC, common.TypeVisibleStr255, do107)
	da108.Value = mms.NewVisibleString("")
	da109 := imodel.NewDataAttribute("swRev", common.FC_DC, common.TypeVisibleStr255, do107)
	da109.Value = mms.NewVisibleString("")
	da110 := imodel.NewDataAttribute("d", common.FC_DC, common.TypeVisibleStr255, do107)
	da110.Value = mms.NewVisibleString("")

	// Logical Node: MMXU2
	ln111 := imodel.NewLogicalNode("MMXU2", ld1)

	do112 := imodel.NewDataObject("Mod", ln111)
	da113 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do112)
	da113.TriggerOptions = common.TriggerQualityChanged
	da113.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da114 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do112)
	da114.Value = mms.NewUTCTime(mms.UTCTime{})
	da115 := imodel.NewDataAttribute("ctlModel", common.FC_CF, common.TypeEnumerated, do112)
	da115.Value = mms.NewInt32(0)

	do116 := imodel.NewDataObject("Beh", ln111)
	da117 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do116)
	da117.TriggerOptions = common.TriggerDataChanged
	da117.Value = mms.NewInt32(0)
	da118 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do116)
	da118.TriggerOptions = common.TriggerQualityChanged
	da118.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da119 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do116)
	da119.Value = mms.NewUTCTime(mms.UTCTime{})

	do120 := imodel.NewDataObject("Health", ln111)
	da121 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do120)
	da121.TriggerOptions = common.TriggerDataChanged
	da121.Value = mms.NewInt32(0)
	da122 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do120)
	da122.TriggerOptions = common.TriggerQualityChanged
	da122.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da123 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do120)
	da123.Value = mms.NewUTCTime(mms.UTCTime{})

	do124 := imodel.NewDataObject("NamPlt", ln111)
	da125 := imodel.NewDataAttribute("vendor", common.FC_DC, common.TypeVisibleStr255, do124)
	da125.Value = mms.NewVisibleString("")
	da126 := imodel.NewDataAttribute("swRev", common.FC_DC, common.TypeVisibleStr255, do124)
	da126.Value = mms.NewVisibleString("")
	da127 := imodel.NewDataAttribute("d", common.FC_DC, common.TypeVisibleStr255, do124)
	da127.Value = mms.NewVisibleString("")

	do128 := imodel.NewDataObject("TotW", ln111)
	da129 := imodel.NewDataAttribute("mag", common.FC_MX, common.TypeConstructed, do128)
	da129.TriggerOptions = common.TriggerDataChanged
	da130 := imodel.NewSubDataAttribute("f", common.FC_MX, common.TypeFLOAT32, da129)
	da130.TriggerOptions = common.TriggerDataChanged
	da130.Value = mms.NewFloat32(0)
	da131 := imodel.NewDataAttribute("q", common.FC_MX, common.TypeQuality, do128)
	da131.TriggerOptions = common.TriggerQualityChanged
	da131.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da132 := imodel.NewDataAttribute("t", common.FC_MX, common.TypeTimestamp, do128)
	da132.Value = mms.NewUTCTime(mms.UTCTime{})

	return iedModel
}
