// Code generated by ModelGenerator gengolibmodel. DO NOT EDIT.

package model

import (
	"github.com/PVKonovalov/libiec61850-Go/pkg/iec61850/common"
	imodel "github.com/PVKonovalov/libiec61850-Go/pkg/iec61850/model"
	"github.com/PVKonovalov/libiec61850-Go/pkg/mms"
)

// BuildModel constructs and returns the IEC 61850 data model.
func BuildModel() *imodel.IedModel {
	iedModel := imodel.NewIedModel("SampleIED")

	// Logical Device: Device1
	ld1 := imodel.NewLogicalDevice("Device1", iedModel)

	// Logical Node: LLN0
	ln2 := imodel.NewLogicalNode("LLN0", ld1)

	do3 := imodel.NewDataObject("Mod", ln2)
	da4 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do3)
	da4.TriggerOptions = common.TriggerQualityChanged
	da4.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da5 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do3)
	da5.Value = mms.NewUTCTime(mms.UTCTime{})
	da6 := imodel.NewDataAttribute("ctlModel", common.FC_CF, common.TypeEnumerated, do3)
	da6.Value = mms.NewInt32(0)

	do7 := imodel.NewDataObject("Beh", ln2)
	da8 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do7)
	da8.TriggerOptions = common.TriggerDataChanged
	da8.Value = mms.NewInt32(0)
	da9 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do7)
	da9.TriggerOptions = common.TriggerQualityChanged
	da9.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da10 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do7)
	da10.Value = mms.NewUTCTime(mms.UTCTime{})

	do11 := imodel.NewDataObject("Health", ln2)
	da12 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do11)
	da12.TriggerOptions = common.TriggerDataChanged
	da12.Value = mms.NewInt32(0)
	da13 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do11)
	da13.TriggerOptions = common.TriggerQualityChanged
	da13.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da14 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do11)
	da14.Value = mms.NewUTCTime(mms.UTCTime{})

	do15 := imodel.NewDataObject("NamPlt", ln2)
	da16 := imodel.NewDataAttribute("vendor", common.FC_DC, common.TypeVisibleStr255, do15)
	da16.Value = mms.NewVisibleString("")
	da17 := imodel.NewDataAttribute("swRev", common.FC_DC, common.TypeVisibleStr255, do15)
	da17.Value = mms.NewVisibleString("")
	da18 := imodel.NewDataAttribute("d", common.FC_DC, common.TypeVisibleStr255, do15)
	da18.Value = mms.NewVisibleString("")
	da19 := imodel.NewDataAttribute("configRev", common.FC_DC, common.TypeVisibleStr255, do15)
	da19.Value = mms.NewVisibleString("")
	da20 := imodel.NewDataAttribute("ldNs", common.FC_EX, common.TypeVisibleStr255, do15)
	da20.Value = mms.NewVisibleString("")

	ds21 := &imodel.DataSet{Name: "LLN0$dataset1"}
	ds21.Members = append(ds21.Members, imodel.DataSetMember{Reference: "Device1/LLN0.Mod.q", FC: common.FC_ST})
	ds21.Members = append(ds21.Members, imodel.DataSetMember{Reference: "Device1/MMXU1.Mod.q", FC: common.FC_ST})
	ds21.Members = append(ds21.Members, imodel.DataSetMember{Reference: "Device1/MMXU1.Mod.ctlModel", FC: common.FC_CF})
	iedModel.DataSets = append(iedModel.DataSets, ds21)

	// Logical Node: LPHD1
	ln22 := imodel.NewLogicalNode("LPHD1", ld1)

	do23 := imodel.NewDataObject("PhyNam", ln22)
	da24 := imodel.NewDataAttribute("vendor", common.FC_DC, common.TypeVisibleStr255, do23)
	da24.Value = mms.NewVisibleString("")

	do25 := imodel.NewDataObject("PhyHealth", ln22)
	da26 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do25)
	da26.TriggerOptions = common.TriggerDataChanged
	da26.Value = mms.NewInt32(0)
	da27 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do25)
	da27.TriggerOptions = common.TriggerQualityChanged
	da27.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da28 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do25)
	da28.Value = mms.NewUTCTime(mms.UTCTime{})

	do29 := imodel.NewDataObject("Proxy", ln22)
	da30 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeBoolean, do29)
	da30.TriggerOptions = common.TriggerDataChanged
	da30.Value = mms.NewBoolean(false)
	da31 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do29)
	da31.TriggerOptions = common.TriggerQualityChanged
	da31.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da32 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do29)
	da32.Value = mms.NewUTCTime(mms.UTCTime{})

	// Logical Node: DGEN1
	ln33 := imodel.NewLogicalNode("DGEN1", ld1)

	do34 := imodel.NewDataObject("Mod", ln33)
	da35 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do34)
	da35.TriggerOptions = common.TriggerQualityChanged
	da35.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da36 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do34)
	da36.Value = mms.NewUTCTime(mms.UTCTime{})
	da37 := imodel.NewDataAttribute("ctlModel", common.FC_CF, common.TypeEnumerated, do34)
	da37.Value = mms.NewInt32(0)

	do38 := imodel.NewDataObject("Beh", ln33)
	da39 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do38)
	da39.TriggerOptions = common.TriggerDataChanged
	da39.Value = mms.NewInt32(0)
	da40 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do38)
	da40.TriggerOptions = common.TriggerQualityChanged
	da40.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da41 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do38)
	da41.Value = mms.NewUTCTime(mms.UTCTime{})

	do42 := imodel.NewDataObject("Health", ln33)
	da43 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do42)
	da43.TriggerOptions = common.TriggerDataChanged
	da43.Value = mms.NewInt32(0)
	da44 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do42)
	da44.TriggerOptions = common.TriggerQualityChanged
	da44.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da45 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do42)
	da45.Value = mms.NewUTCTime(mms.UTCTime{})

	do46 := imodel.NewDataObject("NamPlt", ln33)
	da47 := imodel.NewDataAttribute("vendor", common.FC_DC, common.TypeVisibleStr255, do46)
	da47.Value = mms.NewVisibleString("")
	da48 := imodel.NewDataAttribute("swRev", common.FC_DC, common.TypeVisibleStr255, do46)
	da48.Value = mms.NewVisibleString("")
	da49 := imodel.NewDataAttribute("d", common.FC_DC, common.TypeVisibleStr255, do46)
	da49.Value = mms.NewVisibleString("")

	do50 := imodel.NewDataObject("OpTmh", ln33)
	da51 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do50)
	da51.TriggerOptions = common.TriggerDataChanged
	da51.Value = mms.NewInt32(0)
	da52 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do50)
	da52.TriggerOptions = common.TriggerQualityChanged
	da52.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da53 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do50)
	da53.Value = mms.NewUTCTime(mms.UTCTime{})

	do54 := imodel.NewDataObject("GnOpSt", ln33)
	da55 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do54)
	da55.TriggerOptions = common.TriggerDataChanged
	da55.Value = mms.NewInt32(0)
	da56 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do54)
	da56.TriggerOptions = common.TriggerQualityChanged
	da56.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da57 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do54)
	da57.Value = mms.NewUTCTime(mms.UTCTime{})

	do58 := imodel.NewDataObject("OpTmsRs", ln33)
	da59 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do58)
	da59.TriggerOptions = common.TriggerDataChanged
	da59.Value = mms.NewInt32(0)
	da60 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do58)
	da60.TriggerOptions = common.TriggerQualityChanged
	da60.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da61 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do58)
	da61.Value = mms.NewUTCTime(mms.UTCTime{})

	do62 := imodel.NewDataObject("TotWh", ln33)
	da63 := imodel.NewDataAttribute("mag", common.FC_MX, common.TypeFLOAT32, do62)
	da63.TriggerOptions = common.TriggerDataChanged
	da63.Value = mms.NewFloat32(0)
	da64 := imodel.NewDataAttribute("q", common.FC_MX, common.TypeQuality, do62)
	da64.TriggerOptions = common.TriggerQualityChanged
	da64.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da65 := imodel.NewDataAttribute("t", common.FC_MX, common.TypeTimestamp, do62)
	da65.Value = mms.NewUTCTime(mms.UTCTime{})

	// Logical Node: DSCH1
	ln66 := imodel.NewLogicalNode("DSCH1", ld1)

	do67 := imodel.NewDataObject("Mod", ln66)
	da68 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do67)
	da68.TriggerOptions = common.TriggerQualityChanged
	da68.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da69 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do67)
	da69.Value = mms.NewUTCTime(mms.UTCTime{})
	da70 := imodel.NewDataAttribute("ctlModel", common.FC_CF, common.TypeEnumerated, do67)
	da70.Value = mms.NewInt32(0)

	do71 := imodel.NewDataObject("Beh", ln66)
	da72 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do71)
	da72.TriggerOptions = common.TriggerDataChanged
	da72.Value = mms.NewInt32(0)
	da73 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do71)
	da73.TriggerOptions = common.TriggerQualityChanged
	da73.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da74 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do71)
	da74.Value = mms.NewUTCTime(mms.UTCTime{})

	do75 := imodel.NewDataObject("Health", ln66)
	da76 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do75)
	da76.TriggerOptions = common.TriggerDataChanged
	da76.Value = mms.NewInt32(0)
	da77 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do75)
	da77.TriggerOptions = common.TriggerQualityChanged
	da77.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da78 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do75)
	da78.Value = mms.NewUTCTime(mms.UTCTime{})

	do79 := imodel.NewDataObject("NamPlt", ln66)
	da80 := imodel.NewDataAttribute("vendor", common.FC_DC, common.TypeVisibleStr255, do79)
	da80.Value = mms.NewVisibleString("")
	da81 := imodel.NewDataAttribute("swRev", common.FC_DC, common.TypeVisibleStr255, do79)
	da81.Value = mms.NewVisibleString("")
	da82 := imodel.NewDataAttribute("d", common.FC_DC, common.TypeVisibleStr255, do79)
	da82.Value = mms.NewVisibleString("")

	do83 := imodel.NewDataObject("SchdSt", ln66)
	da84 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do83)
	da84.TriggerOptions = common.TriggerDataChanged
	da84.Value = mms.NewInt32(0)
	da85 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do83)
	da85.TriggerOptions = common.TriggerQualityChanged
	da85.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da86 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do83)
	da86.Value = mms.NewUTCTime(mms.UTCTime{})

	imodel.NewDataObject("SchdId", ln66)

	imodel.NewDataObject("SchdCat", ln66)

	imodel.NewDataObject("SchdTyp", ln66)

	do90 := imodel.NewDataObject("SchdAbsTm", ln66)
	da91 := imodel.NewDataAttribute("val", common.FC_SP, common.TypeFLOAT32, do90)
	da91.TriggerOptions = common.TriggerDataChanged
	da91.Value = mms.NewFloat32(0)
	da92 := imodel.NewDataAttribute("time", common.FC_SP, common.TypeTimestamp, do90)
	da92.TriggerOptions = common.TriggerDataChanged
	da92.Value = mms.NewUTCTime(mms.UTCTime{})

	// Logical Node: MMXU1
	ln93 := imodel.NewLogicalNode("MMXU1", ld1)

	do94 := imodel.NewDataObject("Mod", ln93)
	da95 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do94)
	da95.TriggerOptions = common.TriggerQualityChanged
	da95.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da96 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do94)
	da96.Value = mms.NewUTCTime(mms.UTCTime{})
	da97 := imodel.NewDataAttribute("ctlModel", common.FC_CF, common.TypeEnumerated, do94)
	da97.Value = mms.NewInt32(0)

	do98 := imodel.NewDataObject("Beh", ln93)
	da99 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do98)
	da99.TriggerOptions = common.TriggerDataChanged
	da99.Value = mms.NewInt32(0)
	da100 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do98)
	da100.TriggerOptions = common.TriggerQualityChanged
	da100.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da101 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do98)
	da101.Value = mms.NewUTCTime(mms.UTCTime{})

	do102 := imodel.NewDataObject("Health", ln93)
	da103 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do102)
	da103.TriggerOptions = common.TriggerDataChanged
	da103.Value = mms.NewInt32(0)
	da104 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do102)
	da104.TriggerOptions = common.TriggerQualityChanged
	da104.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da105 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do102)
	da105.Value = mms.NewUTCTime(mms.UTCTime{})

	do106 := imodel.NewDataObject("NamPlt", ln93)
	da107 := imodel.NewDataAttribute("vendor", common.FC_DC, common.TypeVisibleStr255, do106)
	da107.Value = mms.NewVisibleString("")
	da108 := imodel.NewDataAttribute("swRev", common.FC_DC, common.TypeVisibleStr255, do106)
	da108.Value = mms.NewVisibleString("")
	da109 := imodel.NewDataAttribute("d", common.FC_DC, common.TypeVisibleStr255, do106)
	da109.Value = mms.NewVisibleString("")

	// Logical Node: MMXU2
	ln110 := imodel.NewLogicalNode("MMXU2", ld1)

	do111 := imodel.NewDataObject("Mod", ln110)
	da112 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do111)
	da112.TriggerOptions = common.TriggerQualityChanged
	da112.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da113 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do111)
	da113.Value = mms.NewUTCTime(mms.UTCTime{})
	da114 := imodel.NewDataAttribute("ctlModel", common.FC_CF, common.TypeEnumerated, do111)
	da114.Value = mms.NewInt32(0)

	do115 := imodel.NewDataObject("Beh", ln110)
	da116 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do115)
	da116.TriggerOptions = common.TriggerDataChanged
	da116.Value = mms.NewInt32(0)
	da117 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do115)
	da117.TriggerOptions = common.TriggerQualityChanged
	da117.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da118 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do115)
	da118.Value = mms.NewUTCTime(mms.UTCTime{})

	do119 := imodel.NewDataObject("Health", ln110)
	da120 := imodel.NewDataAttribute("stVal", common.FC_ST, common.TypeINT32, do119)
	da120.TriggerOptions = common.TriggerDataChanged
	da120.Value = mms.NewInt32(0)
	da121 := imodel.NewDataAttribute("q", common.FC_ST, common.TypeQuality, do119)
	da121.TriggerOptions = common.TriggerQualityChanged
	da121.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da122 := imodel.NewDataAttribute("t", common.FC_ST, common.TypeTimestamp, do119)
	da122.Value = mms.NewUTCTime(mms.UTCTime{})

	do123 := imodel.NewDataObject("NamPlt", ln110)
	da124 := imodel.NewDataAttribute("vendor", common.FC_DC, common.TypeVisibleStr255, do123)
	da124.Value = mms.NewVisibleString("")
	da125 := imodel.NewDataAttribute("swRev", common.FC_DC, common.TypeVisibleStr255, do123)
	da125.Value = mms.NewVisibleString("")
	da126 := imodel.NewDataAttribute("d", common.FC_DC, common.TypeVisibleStr255, do123)
	da126.Value = mms.NewVisibleString("")

	do127 := imodel.NewDataObject("TotW", ln110)
	da128 := imodel.NewDataAttribute("mag", common.FC_MX, common.TypeFLOAT32, do127)
	da128.TriggerOptions = common.TriggerDataChanged
	da128.Value = mms.NewFloat32(0)
	da129 := imodel.NewDataAttribute("q", common.FC_MX, common.TypeQuality, do127)
	da129.TriggerOptions = common.TriggerQualityChanged
	da129.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)
	da130 := imodel.NewDataAttribute("t", common.FC_MX, common.TypeTimestamp, do127)
	da130.Value = mms.NewUTCTime(mms.UTCTime{})

	return iedModel
}
